"""Добавил в таблицу поле emaile

Revision ID: 75b93e6adbbc
Revises: ca44400059bf
Create Date: 2022-10-21 10:31:28.493964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b93e6adbbc'
down_revision = 'ca44400059bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_estate_ads', sa.Column('email', sa.String(50)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_estate_ads', 'email')
    # ### end Alembic commands ###
